#!/bin/sh

. config/options

if [ -z "$3" ]; then
  echo "usage: $0 package_name file_pattern target_dir"
  exit 1
fi

set_version_dir $1

if [ -f $PACKAGES/$VDIR/url.$TARGET_ARCH ]; then
 URL=url.$TARGET_ARCH
else
 URL=url
fi

[ ! -d "$SOURCES/$1" -o ! -f $PACKAGES/$VDIR/$URL -o ! -d "$3" ] && exit 1

for s in `sed 's%.*/\(.*\)\$%\1%' $PACKAGES/$VDIR/$URL`; do

  case $s in
  $2)  
    f="$SOURCES/$1/$s"
    if [ ! -f $f ]; then
      echo "error: File $s doesn't exists in package $1 sources directory"
      echo "have you called scripts/extract before scripts/get ?"
      exit 1
    fi
    case $s in
      *.tar)
	echo ============== extracting $f ...
        tar xf $f -C $3
        ;;
      *.tar.bz2 | *.tbz)
        echo ============== extracting $f ...
	tar xjf $f -C $3
        ;;
      *.tar.gz | *.tgz)
        echo ============== extracting $f ...
	tar xzf $f -C $3
        ;;
      *.diff | *.patch)
       echo ============== pathing $f ...
       cat $f | patch -d $3 -p1
        ;;
      *.diff.bz2 | *.patch.bz2 | patch-*.bz2)
       echo ============== pathing $f ...
       bzcat $f | patch -d $3 -p1
        ;;
      *.diff.gz | *.patch.gz | patch-*.gz)
       echo ============== pathing $f ...
       zcat $f | patch -d $3 -p1
        ;;
      *)
        cp -pPR $f $3
        ;;
    esac
    ;;
  esac
done
