#!/bin/sh

. config/options

if [ -z "$1" ]; then
  echo "usage: $0 package_name"
  exit 1
fi

echo *-**-**-**-**-**-**-**-**-* prepare unpacking $@ *-**-**-**-**-**-**-**-**-*


$SCRIPTS/get $1

mkdir -p $BUILD

set_version_dir $1

[ ! -d $SOURCES/$1 -a ! -d $PACKAGES/$VDIR/sources ] && exit 0
mkdir -p $STAMPS/$1
STAMP=$STAMPS/$1/unpack

[ -f $STAMP -a -f $PACKAGES/$VDIR/need_unpack ] && $PACKAGES/$VDIR/need_unpack $@
[ -f $STAMP ] && exit 0

printf "%${INDENT}c UNPACK   $1\n" >&$SILENT_OUT
export INDENT=$((${INDENT:-1}+$INDENT_SIZE))

#added by Leo 20070820 to prevent glibc build directory from deleted
if [ "$1" = "glib" ]; then
  rm -rf $BUILD/$1
else
  rm -fr $BUILD/$1*
fi

echo *-**-**-**-**-**-**-**-**-* unpacking $@ *-**-**-**-**-**-**-**-**-*

if [ -f $PACKAGES/$VDIR/url ]; then
  #modified by Leo 2007-6-17  there is no need to check whether the source file name equals $1
  # extract script can get the file name from url file
  $SCRIPTS/extract $1 "*.tar.bz2" $BUILD # "$1*.tar.bz2" $BUILD  
  $SCRIPTS/extract $1 "*.tar.gz"  $BUILD # "$1*.tar.gz"  $BUILD 
  $SCRIPTS/extract $1 "*.tgz"     $BUILD # "$1*.tgz"     $BUILD
fi

[ -f $PACKAGES/$VDIR/after_unpack ] && $PACKAGES/$VDIR/after_unpack $@

if [ -d $PACKAGES/$VDIR/sources ]; then
  [ ! -d $BUILD/$VDIR* ] && mkdir -p $BUILD/$1
  cp -PRf $PACKAGES/$VDIR/sources/* $BUILD/$1*/
fi

if [ -d $PACKAGES/$VDIR/patches.$TARGET_ARCH/ ]; then
    PATCH_DIR=patches.$TARGET_ARCH
else
    PATCH_DIR=patches
fi
for i in $PACKAGES/$VDIR/${PATCH_DIR}/*; do 
 if [ -f $i ]; then
    cat $i | patch -d $BUILD/$1* -p1 >&$VERBOSE_OUT
  fi
done
$SCRIPTS/fixconfigtools $BUILD/$1* #2008.5.5 Leo add * to enable fixtools
[ -f $PACKAGES/$VDIR/unpack ] && $PACKAGES/$VDIR/unpack $@ >&$VERBOSE_OUT

rm -f $STAMPS/$1/build
. $CONFIG/options
for i in `sed -n "s/^\(.*\S\)=\S.*$/\1/p" $CONFIG/options`; do
  eval val=\$$i
  echo STAMP_$i=$val >> $STAMP
done
